#Assumes create-secrets.sh used to create key file, iviaadmin, and cfgsvc secrets
#Assumes verify-access-operator installed from operator hub:
#  curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.32.0/install.sh | bash -s v0.32.0
#  kubectl create -f https://operatorhub.io/install/ibm-security-verify-access-operator.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldaplib
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldapslapd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldapsecauthority
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresqldata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  labels:
    app: openldap
spec:
  selector:
    matchLabels:
      app: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app: openldap
    spec:
      volumes:
        - name: ldaplib
          persistentVolumeClaim:
            claimName: ldaplib
        - name: ldapslapd
          persistentVolumeClaim:
            claimName: ldapslapd
        - name: ldapsecauthority
          persistentVolumeClaim:
            claimName: ldapsecauthority
        - name: openldap-keys
          secret:
            secretName: openldap-keys
      containers:
        - name: openldap
          image: icr.io/isva/verify-access-openldap:10.0.6.0
          livenessProbe:
            tcpSocket:
              port: 636
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 636
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 636
          env:
            - name: LDAP_DOMAIN
              value: ibm.com
            - name: LDAP_ADMIN_PASSWORD
              value: Passw0rd
            - name: LDAP_CONFIG_PASSWORD
              value: Passw0rd
          volumeMounts:
            - mountPath: /var/lib/ldap
              name: ldaplib
            - mountPath: /etc/ldap/slapd.d
              name: ldapslapd
            - mountPath: /var/lib/ldap.secAuthority
              name: ldapsecauthority
            - mountPath: /container/service/slapd/assets/certs
              name: openldap-keys
# This line is needed when running on Kubernetes 1.9.4 or above
          args: [ "--copy-service"]
# useful for debugging startup issues - can run bash, then exec to the container and poke around
#          command: [ "/bin/bash"]
#          args: [ "-c", "while /bin/true ; do sleep 5; done" ]
# Just this line to get debug output from openldap startup
#          args: [ "--loglevel" , "trace","--copy-service"]
---
# for external service access, see https://console.bluemix.net/docs/containers/cs_apps.html#cs_apps_public_nodeport
apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    app: openldap
spec:
  ports:
    - port: 636
      name: ldaps
      protocol: TCP
  selector:
    app: openldap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 70
        fsGroup: 85
      volumes:
        - name: postgresqldata
          persistentVolumeClaim:
            claimName: postgresqldata
        - name: postgresql-keys
          secret:
            secretName: postgresql-keys
      containers:
        - name: postgresql
          image: icr.io/ivia/ivia-postgresql:11.0.2.0
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: Passw0rd
            - name: POSTGRES_DB
              value: ivia
            - name: POSTGRES_SSL_KEYDB
              value: /var/local/server.pem
            - name: PGDATA
              value: /var/lib/postgresql/data/db-files/
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresqldata
            - mountPath: /var/local
              name: postgresql-keys
# useful for debugging startup issues - can run bash, then exec to the container and poke around
#          command: [ "/bin/bash"]
#          args: [ "-c", "while /bin/true ; do sleep 5; done" ]
---
# for external service access, see https://console.bluemix.net/docs/containers/cs_apps.html#cs_apps_public_nodeport
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
    - port: 5432
      name: postgresql
      protocol: TCP
  selector:
    app: postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iviaconfig
  labels:
    app: iviaconfig
spec:
  selector:
    matchLabels:
      app: iviaconfig
  replicas: 1
  template:
    metadata:
      labels:
        app: iviaconfig
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser:    6000
      volumes:
        - name: iviaconfig
          persistentVolumeClaim:
            claimName: iviaconfig
        - name: iviaconfig-logs
          emptyDir: {}
        - name: operator-cert
          secret:
            secretName: verify-access-operator
            items:
            - path: verify-access-operator.crt
              key: tls.cert
      containers:
        - name: iviaconfig
          image: icr.io/ivia/ivia-config:11.0.2.0
          volumeMounts:
            - mountPath: /var/shared
              name: iviaconfig
            - mountPath: /var/application.logs
              name: iviaconfig-logs
            - mountPath: /tmp/verify-access-operator.crt
              name: opeartor-cert
              subPath: verify-access-operator.crt
          env:
            - name: CONTAINER_TIMEZONE
              value: Europe/London
            - name: ADMIN_PWD
              valueFrom:
                secretKeyRef:
                  name: iviaadmin
                  key: adminpw
            - name: CONFIG_SERVICE_ADMIN_PWD
              valueFrom:
                secretKeyRef:
                  name: verify-access-operator
                  key: rw.pwd
            - name: CONFIG_SERVICE_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: verify-access-operator
                  key: user
            - name: CONFIG_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: verify-access-operator
                  key: url
            - name: CONFIG_SERVICE_ADMIN_TLS_CACERT
              value: file:/tmp/verify-access.crt
            - name: SNAPSHOT_ID
              value: operator
          livenessProbe:
            exec:
              command:
              - /sbin/health_check.sh
              - livenessProbe
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          readinessProbe:
            httpGet:
              scheme: HTTPS
              port: 9443
              path: /core/login
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 2
          startupProbe:
            exec:
              command:
              - /sbin/health_check.sh
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 2
#          command: [ "/sbin/bootstrap.sh" ]
---
# for external service access, see https://console.bluemix.net/docs/containers/cs_apps.html#cs_apps_public_nodeport
apiVersion: v1
kind: Service
metadata:
  name: iviaconfig
spec:
# To make the LMI externally visible, make it a nodePort
#  type: NodePort
  ports:
    - port: 9443
      name: iviaconfig
      protocol: TCP
# make this one statically allocated
#      nodePort: 30442
  selector:
    app: iviaconfig
---
apiVersion: ibm.com/v1
kind: IBMSecurityVerifyAccess
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    name: iviawrprp1
  name: iviawrprp1
spec:
  serviceAccountName: default
  image: icr.io/ivia/ivia-wrp:11.0.2.0
  #image: localhost:32000/verify-access-runtime@sha256:2aea752bb257f76715e67ba0f1b104772ee42aeec546df2b52767d37d0fb79a2
  snapshotId: operator
  ilmtAnnotations:
    module: webseal
    production: false
  language: en_US.utf8
  replicas: 1
  instance: 'rp1'
---
# for external service access, see https://console.bluemix.net/docs/containers/cs_apps.html#cs_apps_public_nodeport
apiVersion: v1
kind: Service
metadata:
  name: iviawrprp1
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - port: 9443
      name: iviawrprp1
      protocol: TCP
      nodePort: 30443
  selector:
    app: iviawrprp1
---
apiVersion: ibm.com/v1
kind: IBMSecurityVerifyAccess
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    name: iviaruntime
  name: iviaruntime
spec:
  serviceAccountName: default
  image: icr.io/ivia/ivia-runtime:11.0.2.0
  #image: localhost:32000/verify-access-runtime@sha256:2aea752bb257f76715e67ba0f1b104772ee42aeec546df2b52767d37d0fb79a2
  snapshotId: operator
  ilmtAnnotations:
    module: access_control
    production: false
  language: en_US.utf8
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: iviaruntime
spec:
  ports:
    - port: 9443
      name: iviaruntime
      protocol: TCP
  selector:
    app: iviaruntime
---
apiVersion: ibm.com/v1
kind: IBMSecurityVerifyAccess
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    name: iviadsc
  name: iviadsc
spec:
  serviceAccountName: default
  image: icr.io/ivia/ivia-dsc:11.0.2.0
  #image: localhost:32000/verify-access-runtime@sha256:2aea752bb257f76715e67ba0f1b104772ee42aeec546df2b52767d37d0fb79a2
  snapshotId: operator
  ilmtAnnotations:
    module: webseal
    production: false
  language: en_US.utf8
  replicas: 1
  instance: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: iviadsc
spec:
  ports:
    - port: 9443
      name: iviadsc-svc
      protocol: TCP
    - port: 9444
      name: iviadsc-rep
      protocol: TCP
  selector:
    app: isvadsc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iviaop
  labels:
    app: iviaop
  annotations:
    version: "2.0"
spec:
  selector:
    matchLabels:
      app: iviaop
  replicas: 1
  template: 
    metadata:
      labels:
        app: iviaop
    spec:
      # The name of the service account which has the required
      # capabilities enabled for the IVIAOP container.
      # We use multiple volumes to store the configuration data.
      volumes:
        - name: iviaop-config
          configMap:
            name: iviaop-config
      containers:
        - name: iviaop
          # The fully qualified name of the IVIAOP image.
          image: icr.io/ivia/ivia-oidc-provider:25.10
          imagePullPolicy: Always
          # Mount our volumes to the expected configuration directory
          volumeMounts:
            - name: iviaop-config
              mountPath: /var/isvaop/config
          readinessProbe:
            httpGet:
              path: /healthcheck/ready
              port: 8436
              scheme: HTTPS
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /healthcheck/alive
              port: 8436
              scheme: HTTPS
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: iviaop
  labels:
    app: iviaop
spec:
  ports:
    - port: 8436
      name: iviaop
      nodePort: 31443
  selector:
    app: iviaop
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iviadc
  labels:
    app: iviadc
  annotations:
    version: "2.0"
spec:
  selector:
    matchLabels:
      app: iviadc
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: iviadc
    spec:
      volumes:
        - name: iviadc-config
          configMap:
            name: iviadc-config
      containers:
        - name: iviadc
          # The fully qualified name of the IVIADC image.
          image: icr.io/ivia/ivia-digital-credentials:25.12
          imagePullPolicy: Always
          # Mount our volumes to the expected configuration directory
          volumeMounts:
            - name: iviadc-config
              mountPath: /var/config
          env:
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: "0"
          - name: YAML_FILE
            value: "/var/config/config.yml"
          - name: IBM_API_EXPLORER
            value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: iviadc
  labels:
    app: iviadc
spec:
  ports:
    - port: 9720
      name: iviadc
      nodePort: 30972
  selector:
    app: iviadc
  type: NodePort
